name: mac
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v2
    - name: Setting the environment up.
      run: source configure.sh
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v2
