name: macOS
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: macos-10.15
    steps:
    - uses: actions/checkout@v3
    - name: Setting the environment up.
      run: source configure.sh
