# This is a basic workflow to help you get started with Actions

name: macOS
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: macos-10.15
    steps:
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
